openapi: 3.0.0
info:
  title: aula5
  version: 1.0.0
servers:
  - url: http://{{host}}
paths:
  /pacotes:
    get:
      tags:
        - Pacotes
      summary: Lista pacotes
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pacote'
        default:
          description: Unexpected error
    post:
      tags:
        - Pacotes
      summary: Cria pacote
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Pacote'
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Pacote'
        default:
          description: Unexpected error
  /pacotes/{id}:
    get:
      tags:
        - Pacotes
      summary: Obtem pacote
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Pacote'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        default:
          description: Unexpected error
    delete:
      tags:
        - Pacotes
      summary: Delete pacote
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        "204":
          description: Successful deletion
          content:
            application/json: {}
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        default:
          description: Unexpected error
    put:
      tags:
        - Pacotes
      summary: Altera pacote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pacote'
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pacote'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        default:
            description: Unexpected error
components:
  schemas:
    Localidade:
      type: object
      properties:
        descricao:
          type: string
    Hospedagem:
      allOf:
        - $ref: '#/components/schemas/ItemPacote'
        - type: object
          properties:
            nomeHotel:
              type: string
            endereco:
              type: string
    LocacaoVeiculo:
      allOf:
        - $ref: '#/components/schemas/ItemPacote'
        - type: object
          properties:
            marca:
              type: string
            modelo:
              type: string
    TransladoAereo:
      allOf:
        - $ref: '#/components/schemas/ItemPacote'
        - type: object
          properties:
            companiaAerea:
              type: string
            numeroVoo:
              type: string
    ItemPacote:
      type: object
      properties:
        preco:
          type: number
    Pacote:
      type: object
      properties:
        localidade:
          $ref: '#/components/schemas/Localidade'
        descricao:
          type: string
        items:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/Hospedagem'
              - $ref: '#/components/schemas/LocacaoVeiculo'
              - $ref: '#/components/schemas/TransladoAereo'
        valor:
          type: number
